"""
AIMC-Spec Model Training Module
================================

This file defines the configuration and entrypoint used to train a
specific model architecture on the AIMC-Spec dataset.

Each algorithm in the repository has its own training module with the
same structure as this file. The only components that typically change
between files are:

    • the imported model architecture
    • the `model_name`
    • optional training hyperparameters

The training pipeline itself is shared across all models through the
`run_experiment(...)` function.

----------------------------------------------------------------------
How This File Is Used
----------------------------------------------------------------------

These files are not typically executed directly. Instead, the `main()`
function defined here is imported and executed through the project's
central `main.py` entrypoint.

Example pattern used in `main.py`:

    from src.STFT_CNN.train_stft_cnn import main
    main()

This keeps the experiment orchestration separate from the individual
model configuration files.

----------------------------------------------------------------------
Dataset Requirements
----------------------------------------------------------------------

Training uses the AIMC-Spec memmap dataset generated by the dataset
conversion pipeline. The dataset must already exist before running
training.

Expected dataset location (example):

    C:\\Apps\\Code\\power_specs_memmap\\

This directory should contain memmap files and metadata produced by
the dataset exporter, including:

    power_u8.dat
    yend_u8.dat
    snr_i16.dat
    mod_i16.dat
    stream_i32.dat
    k_u8.dat
    meta.json

These files are loaded internally by the dataset utilities defined in
`src.common`.

----------------------------------------------------------------------
Key Components
----------------------------------------------------------------------

DatasetConfig
    Defines the dataset parameters, including modulation classes,
    SNR levels, dataset path, and loader behaviour.

TrainConfig
    Defines training hyperparameters such as batch sizes, learning
    rate, patience, output directories, and evaluation settings.

MainModel
    The architecture being trained. Each algorithm file imports a
    different model implementation.

run_experiment(...)
    Shared training pipeline that handles:

        • dataset loading
        • training loop
        • validation
        • checkpointing
        • confusion matrix generation
        • logging

----------------------------------------------------------------------
Typical Workflow
----------------------------------------------------------------------

1. Generate AIMC-Spec dataset (HDF5 emitters)
2. Build the train/test subset HDF5 files
3. Export the dataset to memmap spectrogram format
4. Run one of these model training modules

Example experiment run:

    python main.py

----------------------------------------------------------------------
Outputs
----------------------------------------------------------------------

Training produces the following outputs:

    out/<model_name>/
        training logs
        evaluation results
        confusion matrices

    checkpoints/<model_name>/
        model checkpoints
        best-performing weights

----------------------------------------------------------------------
Notes
----------------------------------------------------------------------

• Each algorithm file is intentionally self-contained so experiments
  can be reproduced easily.

• Changing the architecture only requires modifying the model import
  and model initialization.

• All other training logic remains shared through `run_experiment()`.

----------------------------------------------------------------------
Author Context
----------------------------------------------------------------------

This module is part of the AIMC-Spec experimental framework used for
radar intra-pulse modulation classification research.
"""

from __future__ import annotations

import copy
import math
import os
from dataclasses import dataclass, asdict

from datetime import datetime
from pathlib import Path
from typing import Dict, Any

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.optim.lr_scheduler import LambdaLR
import torch.optim as optim
from tqdm import tqdm

from src.LPI_Net.LPI_Net import MainModel
from src.common.config import DatasetConfig, TrainConfig
from src.common.run import run_experiment

try:
    import timm
except Exception as e:
    raise RuntimeError(
        "Please `pip install timm` (and torchvision) to run this baseline."
    ) from e


def main():
    print("|=====| LPI-Net |=====|")
    modulation_list = [
        ###### FM ######
        "unmodulated",
        "lfm_up",
        "lfm_down",
        "dlfm_up_down",
        "NLFM_up",
        "NLFM_down",
        "mlfm",
        "dlfm_down_up",
        ###### PM ######
        "bpsk",
        "qpsk",
        "barker_11",
        "barker_13",
        "p1",
        "p2",
        "p3",
        "p4",
        ### FM ###
        "triangle",
        "exp",
        "bfsk",
        "4fsk",
        "eqfm",
        "sfm",
        "costas",
        ### PM ###
        "barker_2_1",
        "barker_2_2",
        "barker_3",
        "barker_4_1",
        "barker_4_2",
        "barker_5",
        "barker_7",
    ]

    ds_cfg = DatasetConfig(
        modulation_list=modulation_list,
        noise_label="noise",
        snr_range=[6, 3, 0, -3, -6],
        data_path=r"C:\Apps\Code\power_specs_memmap",
        use_noise=False,
        window_count=1,
        window_size=1000,
        window_step_size=1000,
        k_ratio={1: 1.0},
        history_length=1,
        stride=1,
        threshold_time_frac=0.02,
        train_noise_pos_ratio=0.5,
        val_noise_pos_ratio=0.05,
    )

    model_name = "lpi_net"

    train_cfg = TrainConfig(
        seed=42,
        max_epochs=50,
        batch_size_train=32,
        batch_size_val=64,
        learning_rate=1e-3,
        patience=10,
        # min_delta=0.003,
        min_delta=0.001,
        update_every=10,
        ema_alpha=0.1,
        backbone=None,
        pretrained_pt=None,
        out_dir=f"out\\{model_name}\\",
        ckpt_dir=f"checkpoints\\{model_name}\\",
        cm_every_epochs=5,
    )

    num_classes = len(modulation_list) + (1 if ds_cfg.use_noise else 0)
    model = MainModel(num_classes=num_classes)

    train_cfg.criterion = nn.CrossEntropyLoss()

    train_cfg.optimizer = optim.SGD(
        model.parameters(),
        lr=train_cfg.learning_rate,
        momentum=0.9,
        weight_decay=0.0001,
    )

    train_cfg.scheduler = optim.lr_scheduler.StepLR(
        train_cfg.optimizer,
        step_size=45,
        gamma=0.1,
    )

    run_experiment(model=model, ds_cfg=ds_cfg, train_cfg=train_cfg)


if __name__ == "__main__":
    main()
